#! /usr/bin/env python3
import configparser
import os
import sys
from argparse import ArgumentParser

from config import ctx, connect
from models import Document, Keyword

def color(s, code):
    return '\033[%sm%s\033[39m' % (code, s)

def red(s):
    return color(s, 31)

def green(s):
    return color(s, 32)

def blue(s):
    return color(s, 34)

# Action allows to define "routes" names to functions
class Action:

    actions = {}

    def __init__(self, readonly=False):
        self.readonly = readonly

    def __call__(self, fn):
        name = fn.__name__
        self.actions[name] = self
        self.fn = fn
        return fn

    @classmethod
    def get(cls, name, default=None):
        return cls.actions.get(name, default)

    def launch(self, *args, **kwars):
        return self.fn(*args, **kwars)

@Action(readonly=True)
def search(words):
    for doc_id, uri, match, content in Document.search(words):
        if ctx.id:
            print(doc_id)
            continue
        print(red(doc_id), uri)
        print(blue("-> %s" % match))

@Action(readonly=True)
def read(doc_ids):
    for doc_id in doc_ids:
        res = Document.by_id(doc_id)
        if res:
            print(res)

@Action()
def delete(doc_ids):
    for doc_id in doc_ids:
        Document.delete(doc_id)

@Action(readonly=True)
def neighbours(words):
    for res in Keyword.neighbours(words):
        print(res)

@Action(readonly=True)
def suggest(words):
    if not words:
        words =  ['']

    for word in words:
        for res in Keyword.suggest(word):
            print(res.decode())

@Action()
def add(files):
    for f in files:
        Document.add_file(f)

@Action()
def crawl(args):
    Document.crawl()

@Action()
def info(args):
    Document.info()
    Keyword.info()

def main():

    config_file = os.path.expanduser('~/.lvn.cfg')
    config = configparser.ConfigParser()
    # The default optionxform converts key to lowercase
    config.optionxform = str
    config.read(config_file)

    for key in config['main']:
        ctx[key] = config['main'][key]

    parser = ArgumentParser(
        description='Livingstone is a personal search engine',
        add_help=False,
    )
    parser.add_argument('--page', '-p', action='count', help='Go to page',
                        default=0)
    parser.add_argument('--length', '-l', type=int,
                        help='Page length (default: 10)', default=10)
    parser.add_argument('--collect-links', '-c', action='store_true',
                        help='Collect link (do not parse other contents)')
    parser.add_argument('--id', action='store_true', help='Show only id')
    parser.add_argument(
        '--encoding', '-e', help='Define encoding (default: utf-8',
        default='utf-8',
    )

    action_parser= ArgumentParser(parents=[parser])
    action_parser.add_argument('action', nargs='+')

    args, rest = parser.parse_known_args()
    action_args = action_parser.parse_args(rest, args)
    args = vars(args)
    ctx.update(args)

    action_name = args['action'][0]
    action = Action.get(action_name)
    if action is None:
        parser.error('Unknown action "%s"' % action_name)

    ctx.readonly = action.readonly
    with connect('.lvn.db'):
        action.launch(args['action'][1:])

if __name__ == '__main__':
    main()
